/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_use_def_token1 = 1,
  anon_sym_LF = 2,
  sym_package = 3,
  aux_sym_version_token1 = 4,
  aux_sym_version_token2 = 5,
  aux_sym_slot_token1 = 6,
  aux_sym_slot_token2 = 7,
  aux_sym_repository_token1 = 8,
  sym_unset = 9,
  sym_set = 10,
  sym_wildcard = 11,
  sym_cmp = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym_use_def = 15,
  sym_package_identifier = 16,
  sym_version = 17,
  sym_slot = 18,
  sym_repository = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_use_def_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_use_def_token1] = "use_def_token1",
  [anon_sym_LF] = "\n",
  [sym_package] = "package",
  [aux_sym_version_token1] = "version_token1",
  [aux_sym_version_token2] = "version_token2",
  [aux_sym_slot_token1] = "slot_token1",
  [aux_sym_slot_token2] = "slot_token2",
  [aux_sym_repository_token1] = "repository_token1",
  [sym_unset] = "unset",
  [sym_set] = "set",
  [sym_wildcard] = "wildcard",
  [sym_cmp] = "cmp",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_use_def] = "use_def",
  [sym_package_identifier] = "package_identifier",
  [sym_version] = "version",
  [sym_slot] = "slot",
  [sym_repository] = "repository",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_use_def_repeat1] = "use_def_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_use_def_token1] = aux_sym_use_def_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_package] = sym_package,
  [aux_sym_version_token1] = aux_sym_version_token1,
  [aux_sym_version_token2] = aux_sym_version_token2,
  [aux_sym_slot_token1] = aux_sym_slot_token1,
  [aux_sym_slot_token2] = aux_sym_slot_token2,
  [aux_sym_repository_token1] = aux_sym_repository_token1,
  [sym_unset] = sym_unset,
  [sym_set] = sym_set,
  [sym_wildcard] = sym_wildcard,
  [sym_cmp] = sym_cmp,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_use_def] = sym_use_def,
  [sym_package_identifier] = sym_package_identifier,
  [sym_version] = sym_version,
  [sym_slot] = sym_slot,
  [sym_repository] = sym_repository,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_use_def_repeat1] = aux_sym_use_def_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_use_def_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_version_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_version_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_repository_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_unset] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_def] = {
    .visible = true,
    .named = true,
  },
  [sym_package_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_slot] = {
    .visible = true,
    .named = true,
  },
  [sym_repository] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_use_def_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 18,
        '#', 34,
        '*', 6,
        '-', 21,
        ':', 25,
        '<', 33,
        '>', 33,
        '_', 26,
        '=', 32,
        '~', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '-') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '-') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '#', 34,
        '*', 6,
        '-', 21,
        ':', 25,
        '<', 33,
        '>', 33,
        '=', 32,
        '~', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_use_def_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_package);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_package);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_version_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_version_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_slot_token1);
      if (lookahead == ':') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_repository_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_unset);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_set);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_cmp);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_cmp);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_use_def_token1] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
    [sym_package] = ACTIONS(1),
    [aux_sym_version_token1] = ACTIONS(1),
    [aux_sym_slot_token1] = ACTIONS(1),
    [aux_sym_slot_token2] = ACTIONS(1),
    [aux_sym_repository_token1] = ACTIONS(1),
    [sym_set] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_cmp] = ACTIONS(1),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_use_def] = STATE(2),
    [sym_package_identifier] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [aux_sym_use_def_token1] = ACTIONS(5),
    [sym_package] = ACTIONS(9),
    [sym_wildcard] = ACTIONS(11),
    [sym_cmp] = ACTIONS(13),
    [sym_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      sym_package,
    ACTIONS(11), 1,
      sym_wildcard,
    ACTIONS(13), 1,
      sym_cmp,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_package_identifier,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    STATE(3), 2,
      sym_use_def,
      aux_sym_source_file_repeat1,
  [24] = 7,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_package,
    ACTIONS(22), 1,
      sym_wildcard,
    ACTIONS(25), 1,
      sym_cmp,
    STATE(22), 1,
      sym_package_identifier,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    STATE(3), 2,
      sym_use_def,
      aux_sym_source_file_repeat1,
  [48] = 8,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(28), 1,
      aux_sym_use_def_token1,
    ACTIONS(30), 1,
      aux_sym_version_token1,
    ACTIONS(32), 1,
      aux_sym_slot_token1,
    ACTIONS(34), 1,
      aux_sym_repository_token1,
    STATE(5), 1,
      sym_version,
    STATE(14), 1,
      sym_slot,
    STATE(23), 1,
      sym_repository,
  [73] = 6,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(32), 1,
      aux_sym_slot_token1,
    ACTIONS(34), 1,
      aux_sym_repository_token1,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
    STATE(16), 1,
      sym_slot,
    STATE(25), 1,
      sym_repository,
  [92] = 5,
    ACTIONS(3), 1,
      aux_sym_use_def_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(40), 2,
      sym_unset,
      sym_set,
  [109] = 5,
    ACTIONS(3), 1,
      aux_sym_use_def_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(40), 2,
      sym_unset,
      sym_set,
  [126] = 2,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(44), 4,
      ts_builtin_sym_end,
      sym_package,
      sym_wildcard,
      sym_cmp,
  [137] = 5,
    ACTIONS(3), 1,
      aux_sym_use_def_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(48), 2,
      sym_unset,
      sym_set,
  [154] = 2,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      sym_package,
      sym_wildcard,
      sym_cmp,
  [165] = 4,
    ACTIONS(9), 1,
      sym_package,
    ACTIONS(53), 1,
      sym_wildcard,
    STATE(27), 1,
      sym_package_identifier,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [179] = 3,
    STATE(7), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(55), 2,
      sym_unset,
      sym_set,
  [191] = 3,
    STATE(6), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(57), 2,
      sym_unset,
      sym_set,
  [203] = 4,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(34), 1,
      aux_sym_repository_token1,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
    STATE(25), 1,
      sym_repository,
  [216] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(61), 1,
      aux_sym_slot_token1,
    ACTIONS(59), 2,
      aux_sym_use_def_token1,
      aux_sym_repository_token1,
  [227] = 4,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(34), 1,
      aux_sym_repository_token1,
    ACTIONS(63), 1,
      aux_sym_use_def_token1,
    STATE(24), 1,
      sym_repository,
  [240] = 2,
    ACTIONS(65), 1,
      aux_sym_version_token2,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [248] = 2,
    ACTIONS(67), 1,
      aux_sym_slot_token2,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [256] = 2,
    ACTIONS(69), 1,
      aux_sym_slot_token2,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [264] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [272] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(73), 2,
      aux_sym_use_def_token1,
      aux_sym_repository_token1,
  [280] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_use_def_token1,
  [287] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
  [294] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_use_def_token1,
  [301] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(63), 1,
      aux_sym_use_def_token1,
  [308] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(79), 1,
      aux_sym_use_def_token1,
  [315] = 2,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(81), 1,
      aux_sym_use_def_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 109,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 154,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 179,
  [SMALL_STATE(13)] = 191,
  [SMALL_STATE(14)] = 203,
  [SMALL_STATE(15)] = 216,
  [SMALL_STATE(16)] = 227,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 248,
  [SMALL_STATE(19)] = 256,
  [SMALL_STATE(20)] = 264,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 280,
  [SMALL_STATE(23)] = 287,
  [SMALL_STATE(24)] = 294,
  [SMALL_STATE(25)] = 301,
  [SMALL_STATE(26)] = 308,
  [SMALL_STATE(27)] = 315,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_def, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_use_def_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_use_def_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_def, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repository, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_use(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "use",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
