/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_use_def_token1 = 2,
  aux_sym_version_token1 = 3,
  aux_sym_version_token2 = 4,
  aux_sym_slot_token1 = 5,
  aux_sym_slot_token2 = 6,
  aux_sym_repository_token1 = 7,
  sym_unset = 8,
  sym_set = 9,
  aux_sym_package_token1 = 10,
  anon_sym_SLASH = 11,
  aux_sym_package_token2 = 12,
  sym_wildcard = 13,
  sym_cmp = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_use_def = 17,
  sym_package_identifier = 18,
  sym_version = 19,
  sym_slot = 20,
  sym_repository = 21,
  sym_package = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_use_def_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_use_def_token1] = "use_def_token1",
  [aux_sym_version_token1] = "version_token1",
  [aux_sym_version_token2] = "version_token2",
  [aux_sym_slot_token1] = "slot_token1",
  [aux_sym_slot_token2] = "slot_token2",
  [aux_sym_repository_token1] = "repository_token1",
  [sym_unset] = "unset",
  [sym_set] = "set",
  [aux_sym_package_token1] = "package_token1",
  [anon_sym_SLASH] = "/",
  [aux_sym_package_token2] = "package_token2",
  [sym_wildcard] = "wildcard",
  [sym_cmp] = "cmp",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_use_def] = "use_def",
  [sym_package_identifier] = "package_identifier",
  [sym_version] = "version",
  [sym_slot] = "slot",
  [sym_repository] = "repository",
  [sym_package] = "package",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_use_def_repeat1] = "use_def_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_use_def_token1] = aux_sym_use_def_token1,
  [aux_sym_version_token1] = aux_sym_version_token1,
  [aux_sym_version_token2] = aux_sym_version_token2,
  [aux_sym_slot_token1] = aux_sym_slot_token1,
  [aux_sym_slot_token2] = aux_sym_slot_token2,
  [aux_sym_repository_token1] = aux_sym_repository_token1,
  [sym_unset] = sym_unset,
  [sym_set] = sym_set,
  [aux_sym_package_token1] = aux_sym_package_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym_package_token2] = aux_sym_package_token2,
  [sym_wildcard] = sym_wildcard,
  [sym_cmp] = sym_cmp,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_use_def] = sym_use_def,
  [sym_package_identifier] = sym_package_identifier,
  [sym_version] = sym_version,
  [sym_slot] = sym_slot,
  [sym_repository] = sym_repository,
  [sym_package] = sym_package,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_use_def_repeat1] = aux_sym_use_def_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_use_def_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_version_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_version_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_repository_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_unset] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_package_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_package_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_def] = {
    .visible = true,
    .named = true,
  },
  [sym_package_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_slot] = {
    .visible = true,
    .named = true,
  },
  [sym_repository] = {
    .visible = true,
    .named = true,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_use_def_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '#', 61,
        '*', 6,
        '/', 52,
        '<', 60,
        '>', 60,
        '_', 38,
        '=', 59,
        '~', 59,
      );
      if (('[' <= lookahead && lookahead <= '`')) ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '#') ADVANCE(61);
      if (lookahead == '-') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(61);
      if (lookahead == '-') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'p') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '#', 61,
        '*', 6,
        '-', 21,
        '/', 52,
        ':', 34,
        '<', 60,
        '>', 60,
        '=', 59,
        '~', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_use_def_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_version_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_version_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+') ADVANCE(41);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(51);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+') ADVANCE(12);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '_') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+') ADVANCE(39);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == '_') ADVANCE(35);
      if (('[' <= lookahead && lookahead <= '`')) ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '_') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '+' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '+' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_version_token2);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_slot_token1);
      if (lookahead == ':') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == 'p') ADVANCE(23);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == 'r') ADVANCE(40);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '.') ADVANCE(51);
      if (('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`') ADVANCE(55);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_slot_token2);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_repository_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unset);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_set);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (lookahead == 'p') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (lookahead == 'r') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_package_token1);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (lookahead == '#') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (lookahead == 'p') ADVANCE(24);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_package_token2);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_cmp);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_cmp);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 53},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_use_def_token1] = ACTIONS(3),
    [aux_sym_version_token2] = ACTIONS(1),
    [aux_sym_slot_token2] = ACTIONS(1),
    [sym_set] = ACTIONS(1),
    [aux_sym_package_token1] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [aux_sym_package_token2] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_cmp] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_use_def] = STATE(19),
    [sym_package_identifier] = STATE(25),
    [sym_package] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_use_def_token1] = ACTIONS(3),
    [aux_sym_package_token1] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(9),
    [sym_cmp] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      aux_sym_package_token1,
    ACTIONS(9), 1,
      sym_wildcard,
    ACTIONS(11), 1,
      sym_cmp,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(4), 1,
      sym_package,
    STATE(19), 1,
      sym_use_def,
    STATE(25), 1,
      sym_package_identifier,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [29] = 9,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      aux_sym_package_token1,
    ACTIONS(20), 1,
      sym_wildcard,
    ACTIONS(23), 1,
      sym_cmp,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(4), 1,
      sym_package,
    STATE(19), 1,
      sym_use_def,
    STATE(25), 1,
      sym_package_identifier,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [58] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      aux_sym_use_def_token1,
    ACTIONS(28), 1,
      aux_sym_version_token1,
    ACTIONS(30), 1,
      aux_sym_slot_token1,
    ACTIONS(32), 1,
      aux_sym_repository_token1,
    STATE(7), 1,
      sym_version,
    STATE(14), 1,
      sym_slot,
    STATE(27), 1,
      sym_repository,
  [83] = 5,
    ACTIONS(7), 1,
      aux_sym_package_token1,
    ACTIONS(34), 1,
      sym_wildcard,
    STATE(4), 1,
      sym_package,
    STATE(26), 1,
      sym_package_identifier,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [100] = 2,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      aux_sym_package_token1,
      sym_wildcard,
      sym_cmp,
  [111] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      aux_sym_slot_token1,
    ACTIONS(32), 1,
      aux_sym_repository_token1,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
    STATE(15), 1,
      sym_slot,
    STATE(29), 1,
      sym_repository,
  [130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_LF,
    ACTIONS(40), 1,
      aux_sym_use_def_token1,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(42), 2,
      sym_unset,
      sym_set,
  [147] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      aux_sym_use_def_token1,
    ACTIONS(44), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(46), 2,
      sym_unset,
      sym_set,
  [164] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      aux_sym_use_def_token1,
    ACTIONS(49), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(42), 2,
      sym_unset,
      sym_set,
  [181] = 3,
    STATE(8), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(51), 2,
      sym_unset,
      sym_set,
  [193] = 3,
    STATE(10), 1,
      aux_sym_use_def_repeat1,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
    ACTIONS(53), 2,
      sym_unset,
      sym_set,
  [205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      aux_sym_slot_token1,
    ACTIONS(55), 3,
      aux_sym_use_def_token1,
      aux_sym_version_token1,
      aux_sym_repository_token1,
  [217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      aux_sym_repository_token1,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
    STATE(29), 1,
      sym_repository,
  [230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      aux_sym_repository_token1,
    ACTIONS(59), 1,
      aux_sym_use_def_token1,
    STATE(30), 1,
      sym_repository,
  [243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      aux_sym_slot_token1,
    ACTIONS(61), 2,
      aux_sym_use_def_token1,
      aux_sym_repository_token1,
  [254] = 2,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [262] = 2,
    ACTIONS(67), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [270] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      aux_sym_use_def_token1,
    ACTIONS(69), 1,
      anon_sym_LF,
  [280] = 2,
    ACTIONS(71), 1,
      aux_sym_package_token2,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [288] = 2,
    ACTIONS(73), 1,
      aux_sym_version_token2,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [296] = 2,
    ACTIONS(75), 1,
      aux_sym_slot_token2,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [304] = 2,
    ACTIONS(77), 1,
      aux_sym_slot_token2,
    ACTIONS(3), 2,
      aux_sym_use_def_token1,
      sym_comment,
  [312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      aux_sym_use_def_token1,
      aux_sym_repository_token1,
  [320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      aux_sym_use_def_token1,
  [327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      aux_sym_use_def_token1,
  [334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      aux_sym_use_def_token1,
  [341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_use_def_token1,
  [348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      aux_sym_use_def_token1,
  [355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_use_def_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 83,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 111,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 147,
  [SMALL_STATE(10)] = 164,
  [SMALL_STATE(11)] = 181,
  [SMALL_STATE(12)] = 193,
  [SMALL_STATE(13)] = 205,
  [SMALL_STATE(14)] = 217,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 243,
  [SMALL_STATE(17)] = 254,
  [SMALL_STATE(18)] = 262,
  [SMALL_STATE(19)] = 270,
  [SMALL_STATE(20)] = 280,
  [SMALL_STATE(21)] = 288,
  [SMALL_STATE(22)] = 296,
  [SMALL_STATE(23)] = 304,
  [SMALL_STATE(24)] = 312,
  [SMALL_STATE(25)] = 320,
  [SMALL_STATE(26)] = 327,
  [SMALL_STATE(27)] = 334,
  [SMALL_STATE(28)] = 341,
  [SMALL_STATE(29)] = 348,
  [SMALL_STATE(30)] = 355,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_def, 3, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_use_def_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_use_def_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_def, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repository, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_identifier, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_use(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "use",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
